set(SOURCES
    SOURCE/HELPERS/CsvLoader.cpp
    SOURCE/HELPERS/CsvLoader.h
    SOURCE/INTERPOLATOR/Interpolator.h
    SOURCE/OSCILLATOR/Oscillator.cpp
    SOURCE/OSCILLATOR/Oscillator.h
    SOURCE/PULSAR/PulsarSynth.cpp
    SOURCE/PULSAR/PulsarSynth.h
    SOURCE/PULSAR/PulsarVoice.cpp
    SOURCE/PULSAR/PulsarVoice.h
    SOURCE/RD_BUFFER/BufferFiller.cpp
    SOURCE/RD_BUFFER/BufferFiller.h
    SOURCE/RD_BUFFER/RD_Buffer.cpp
    SOURCE/RD_BUFFER/RD_Buffer.h
    SOURCE/SYNTH/Synth.cpp
    SOURCE/SYNTH/Synth.h
    SOURCE/SYNTH/SynthVoice.cpp
    SOURCE/SYNTH/SynthVoice.h
    SOURCE/WAVEFORM/WaveFactory.cpp
    SOURCE/WAVEFORM/WaveFactory.h
    SOURCE/WAVEFORM/Waveform.cpp
    SOURCE/WAVEFORM/Waveform.h
    SOURCE/WAVEFORM/Wavetable.cpp
    SOURCE/WAVEFORM/Wavetable.h
)