set(SOURCES
    SOURCE/HELPERS/CsvLoader.cpp
    SOURCE/HELPERS/CsvLoader.h
    SOURCE/INTERPOLATOR/Interpolator.h
    SOURCE/OSCILLATOR/Oscillator.cpp
    SOURCE/OSCILLATOR/Oscillator.h
    SOURCE/RD_BUFFER/BufferFiller.cpp
    SOURCE/RD_BUFFER/BufferFiller.h
    SOURCE/RD_BUFFER/RD_Buffer.cpp
    SOURCE/RD_BUFFER/RD_Buffer.h
    SOURCE/WAVEFORM/WaveFactory.cpp
    SOURCE/WAVEFORM/WaveFactory.h
    SOURCE/WAVEFORM/Waveform.cpp
    SOURCE/WAVEFORM/Waveform.h
    SOURCE/WAVEFORM/Wavetable.cpp
    SOURCE/WAVEFORM/Wavetable.h
)