set(TEST_SOURCES
    TESTS/HELPERS/CsvLoader.cpp
    TESTS/HELPERS/CsvLoader.h
    TESTS/OSCILLATOR/test_Oscillator.cpp
    TESTS/RD_BUFFER/test_RD_Buffer.cpp
    TESTS/WAVEFORM/test_Waveform.cpp
    TESTS/test_Waveform.cpp
    TESTS/test_main.cpp
)