set(TEST_SOURCES
    TESTS/BUFFER_FILLER/test_BufferFiller_fromCSV.cpp
    TESTS/OSCILLATOR/test_Oscillator.cpp
    TESTS/PULSAR/test_PulsarSynth.cpp
    TESTS/PULSAR/test_PulsarVoice.cpp
    TESTS/RD_BUFFER/test_BufferFiller.cpp
    TESTS/RD_BUFFER/test_RD_Buffer.cpp
    TESTS/SYNTH/test_Synth.cpp
    TESTS/SYNTH/test_SynthVoice.cpp
    TESTS/WAVEFORM/test_WaveFactory.cpp
    TESTS/WAVEFORM/test_Waveform.cpp
    TESTS/WAVEFORM/test_Wavetable.cpp
    TESTS/test_Waveform.cpp
    TESTS/test_main.cpp
)